name: vibecoding_vibenet
description: VibeNet - social ambientale con chat e stanze private/pubbliche
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  collection: ^1.18.0
  provider: ^6.0.5
  path_provider: ^2.1.3
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.2
  audioplayers: ^6.0.0
  record: ^5.1.0
  firebase_storage: ^12.0.0
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  speech_to_text: ^6.6.2

  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: main


# dependency_overrides:
#   flutter_webrtc: 0.9.27



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ambient.mp3
